In [1]:
def AND(x1,x2):
    w1, w2, theta = 0.5, 0.5, 0.7
    tmp = x1*w1 + x2*w2
    if tmp <= theta:
        return 0
    elif tmp > theta:
        return 1

print(AND(0,0))
print(AND(1,0))
print(AND(0,1))
print(AND(1,1))

0
0
0
1


In [2]:
import numpy as np

x = np.array([0,1])
w = np.array([0.5, 0.5])
b = -0.7

print(w*x)
print(np.sum(w*x))
print(np.sum(w*x) + b)

[0.  0.5]
0.5
-0.19999999999999996


In [3]:
# x should be  1 or 0
def AND(x1,x2):
    x = np.array([x1,x2])
    w = np.array([0.5,0.5])
    b = -0.7
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1

def NAND(x1,x2):
    x = np.array([x1,x2])
    w = np.array([-0.5,-0.5])
    b = 0.7
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1

def OR(x1,x2):
    x = np.array([x1,x2])
    w = np.array([0.5,0.5])
    b = -0.2
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1

def XOR(x1,x2):
    s1 = NAND(x1,x2)
    s2 = OR(x1,x2)
    y = AND(s1,s2)
    return y

print(XOR(0,0))
print(XOR(1,0))
print(XOR(0,1))
print(XOR(1,1))

0
1
1
0


In [4]:
import numpy as np

# シードを設定
np.random.seed(42)

# 5個の4x2pxのランダムな画像データを生成
# 範囲は0から255までの整数
x = np.random.randint(0, 256, size=(5, 4, 2))

# xの内容の具体例（最初の２つの画像を表示）
print(x[:2])


[[[102 179]
  [ 92  14]
  [106  71]
  [188  20]]

 [[102 121]
  [210 214]
  [ 74 202]
  [ 87 116]]]


In [5]:
import numpy as np

# シードを設定
np.random.seed(42)

# 上記の5個の4x2pxの画像が平坦化されたデータ
# 範囲は0から255までの整数
x = np.random.randint(0, 256, size=(5, 8))

# xの内容の具体例（最初の2つの画像データを表示）
print(x[:2])


[[102 179  92  14 106  71 188  20]
 [102 121 210 214  74 202  87 116]]


In [6]:
import numpy as np

# シードを設定
np.random.seed(42)

# 5個の1チャンネル(Grey)をもった4x2pxのランダムな画像データを生成([]が増えただけで内容は１番目と上記と変わらない)
# 範囲は0から255までの整数
x = np.random.randint(0, 256, size=(5, 1, 4, 2))

# xの内容の具体例（最初の２つの画像データを表示）
print(x[:2])


[[[[102 179]
   [ 92  14]
   [106  71]
   [188  20]]]


 [[[102 121]
   [210 214]
   [ 74 202]
   [ 87 116]]]]


In [7]:
import numpy as np

# シードを設定
np.random.seed(42)

# 5個の3チャンネル(RGB)をもった4x2pxのランダムな画像データを生成
# 範囲は0から255までの整数
x = np.random.randint(0, 256, size=(5, 3, 4, 2))

# xの内容の具体例（最初の２つの画像データを表示）
print(x[:2])

[[[[102 179]
   [ 92  14]
   [106  71]
   [188  20]]

  [[102 121]
   [210 214]
   [ 74 202]
   [ 87 116]]

  [[ 99 103]
   [151 130]
   [149  52]
   [  1  87]]]


 [[[235 157]
   [ 37 129]
   [191 187]
   [ 20 160]]

  [[203  57]
   [ 21 252]
   [235  88]
   [ 48 218]]

  [[ 58 254]
   [169 255]
   [219 187]
   [207  14]]]]
